# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sh_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Message(object):
    def setupUi(self, Message):
        Message.setObjectName("Message")
        Message.resize(1000,1000)
        Message.setMinimumSize(QtCore.QSize(1000,1000))
        Message.setMaximumSize(QtCore.QSize(1000,1000))
        self.pushButton = QtWidgets.QPushButton(Message)
        self.pushButton.setGeometry(QtCore.QRect(120, 140, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.mess = QtWidgets.QLabel(Message)
        self.mess.setGeometry(QtCore.QRect(20, 20, 361, 111))
        self.mess.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.mess.setObjectName("mess")

        self.retranslateUi(Message)
        QtCore.QMetaObject.connectSlotsByName(Message)

    def retranslateUi(self, Message):
        _translate = QtCore.QCoreApplication.translate
        Message.setWindowTitle(_translate("Message", "Сообщение"))
        self.pushButton.setText(_translate("Message", "Я понял"))
        self.mess.setText(_translate("Message", "Тут текст"))
