# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'third.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Checker(object):
    def setupUi(self, Checker):
        Checker.setObjectName("Checker")
        Checker.resize(1170, 720)
        Checker.setMinimumSize(QtCore.QSize(1170, 720))
        Checker.setMaximumSize(QtCore.QSize(1170, 720))
        self.background = QtWidgets.QLabel(Checker)
        self.background.setGeometry(QtCore.QRect(-6, -5, 1181, 731))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("../Snapit-App-Background.png"))
        self.background.setObjectName("background")
        self.topic = QtWidgets.QLabel(Checker)
        self.topic.setGeometry(QtCore.QRect(400, 10, 331, 91))
        self.topic.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.topic.setObjectName("topic")
        self.question_text = QtWidgets.QLabel(Checker)
        self.question_text.setGeometry(QtCore.QRect(50, 140, 341, 61))
        self.question_text.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.question_text.setObjectName("question_text")
        self.groupBox = QtWidgets.QGroupBox(Checker)
        self.groupBox.setGeometry(QtCore.QRect(40, 230, 1031, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ans0 = QtWidgets.QRadioButton(self.groupBox)
        self.ans0.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.ans0.setObjectName("ans0")
        self.verticalLayout.addWidget(self.ans0)
        self.ans1 = QtWidgets.QRadioButton(self.groupBox)
        self.ans1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.ans1.setObjectName("ans1")
        self.verticalLayout.addWidget(self.ans1)
        self.ans2 = QtWidgets.QRadioButton(self.groupBox)
        self.ans2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.ans2.setObjectName("ans2")
        self.verticalLayout.addWidget(self.ans2)
        self.ans3 = QtWidgets.QRadioButton(self.groupBox)
        self.ans3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.ans3.setObjectName("ans3")
        self.verticalLayout.addWidget(self.ans3)
        self.pccc = QtWidgets.QLabel(Checker)
        self.pccc.setGeometry(QtCore.QRect(40, 550, 241, 161))
        self.pccc.setText("")
        self.pccc.setPixmap(QtGui.QPixmap("../pc1.png"))
        self.pccc.setObjectName("pccc")
        self.next_que = QtWidgets.QPushButton(Checker)
        self.next_que.setGeometry(QtCore.QRect(790, 580, 281, 81))
        self.next_que.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.next_que.setObjectName("next_que")
        self.next_que_2 = QtWidgets.QPushButton(Checker)
        self.next_que_2.setGeometry(QtCore.QRect(480, 580, 281, 81))
        self.next_que_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.next_que_2.setObjectName("next_que_2")
        self.next_que_3 = QtWidgets.QPushButton(Checker)
        self.next_que_3.setGeometry(QtCore.QRect(410, 330, 351, 91))
        self.next_que_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.next_que_3.setObjectName("next_que_3")

        self.retranslateUi(Checker)
        QtCore.QMetaObject.connectSlotsByName(Checker)

    def retranslateUi(self, Checker):
        _translate = QtCore.QCoreApplication.translate
        Checker.setWindowTitle(_translate("Checker", "Тестирование"))
        self.topic.setText(_translate("Checker", "Вопрос № /"))
        self.question_text.setText(_translate("Checker", "Тут вопрос"))
        self.ans0.setText(_translate("Checker", "первый вариант ответа"))
        self.ans1.setText(_translate("Checker", "второй вариант ответа"))
        self.ans2.setText(_translate("Checker", "третий вариант ответа"))
        self.ans3.setText(_translate("Checker", "четвертый вариант ответа"))
        self.next_que.setText(_translate("Checker", "Ответить"))
        self.next_que_2.setText(_translate("Checker", "Пропустить"))
        self.next_que_3.setText(_translate("Checker", "Начать тест"))
