# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fourth.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_End(object):
    def setupUi(self, End):
        End.setObjectName("End")
        End.resize(1170, 720)
        End.setMinimumSize(QtCore.QSize(1170, 720))
        End.setMaximumSize(QtCore.QSize(1170, 720))
        self.label = QtWidgets.QLabel(End)
        self.label.setGeometry(QtCore.QRect(-6, -5, 1181, 731))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Snapit-App-Background.png"))
        self.label.setObjectName("label")
        self.ret = QtWidgets.QPushButton(End)
        self.ret.setGeometry(QtCore.QRect(400, 570, 361, 101))
        self.ret.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.ret.setObjectName("ret")
        self.topic = QtWidgets.QLabel(End)
        self.topic.setGeometry(QtCore.QRect(480, 10, 261, 91))
        self.topic.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.topic.setObjectName("topic")
        self.pcccccc = QtWidgets.QLabel(End)
        self.pcccccc.setGeometry(QtCore.QRect(810, 200, 271, 231))
        self.pcccccc.setText("")
        self.pcccccc.setPixmap(QtGui.QPixmap("pc1.png"))
        self.pcccccc.setObjectName("pcccccc")
        self.show_results = QtWidgets.QPushButton(End)
        self.show_results.setGeometry(QtCore.QRect(420, 330, 361, 151))
        self.show_results.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.show_results.setObjectName("show_results")
        self.res = QtWidgets.QPlainTextEdit(End)
        self.res.setGeometry(QtCore.QRect(20, 200, 551, 361))
        self.res.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.res.setReadOnly(True)
        self.res.setReadOnly(True)
        self.res.setObjectName("res")
        self.label.raise_()
        self.ret.raise_()
        self.topic.raise_()
        self.pcccccc.raise_()
        self.res.raise_()
        self.show_results.raise_()

        self.retranslateUi(End)
        QtCore.QMetaObject.connectSlotsByName(End)

    def retranslateUi(self, End):
        _translate = QtCore.QCoreApplication.translate
        End.setWindowTitle(_translate("End", "Результаты"))
        self.ret.setText(_translate("End", "Вернуться к генератору"))
        self.topic.setText(_translate("End", "Результаты теста"))
        self.show_results.setText(_translate("End", "Показать результаты"))
