# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fourth.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_End(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1170, 720)
        Form.setMinimumSize(QtCore.QSize(1170, 720))
        Form.setMaximumSize(QtCore.QSize(1170, 720))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-6, -5, 1181, 731))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Snapit-App-Background.png"))
        self.label.setObjectName("label")
        self.ret = QtWidgets.QPushButton(Form)
        self.ret.setGeometry(QtCore.QRect(400, 570, 361, 101))
        self.ret.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.ret.setObjectName("ret")
        self.topic = QtWidgets.QLabel(Form)
        self.topic.setGeometry(QtCore.QRect(380, 10, 261, 91))
        self.topic.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.topic.setObjectName("topic")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 160, 641, 301))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 639, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pcccccc = QtWidgets.QLabel(Form)
        self.pcccccc.setGeometry(QtCore.QRect(810, 200, 271, 231))
        self.pcccccc.setText("")
        self.pcccccc.setPixmap(QtGui.QPixmap("pc1.png"))
        self.pcccccc.setObjectName("pcccccc")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("End", "Результаты"))
        self.ret.setText(_translate("Form", "Вернуться к генератору"))
        self.topic.setText(_translate("Form", "Результаты теста"))
